### ISSUE TITLE
Trying to build with VS, it throws 3k errors 

### ISSUE THREAD

**Issue by smugvee** [es3n1n/portal2-internal#1]
^^^
![image](https://user-images.githubusercontent.com/85663797/147329049-658b0ef0-6126-48c7-b61f-795d00ec7eb1.png)

**Comment by es3n1n** [comment]
why would you compile it in x64 when game is x86 🤔

**Comment by smugvee** [comment]
🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔
thanks, im stupid
