### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by kehrazy** [es3n1n/portal2-internal#17]
a modern sdk should have cmake support, because vcxproj is xml bullshit.

**Comment by kehrazy** [comment]
I am going to take this (assign pls).

I would suggest using [cmkr](https://cmkr.build), seeing as it is the superior CMakeFiless generator.

**Comment by es3n1n** [comment]
> because vcxproj is xml bullshit.

can't argue with that

> I am going to take this (assign pls).

here you go

> I would suggest using [cmkr](https://cmkr.build), seeing as it is the superior CMakeFiless generator.

yeah, cmkr ftw
