### ISSUE TITLE
use std::move whenever possible

### ISSUE THREAD

**Issue by kehrazy** [es3n1n/portal2-internal#21]
performance is cool

**Comment by kehrazy** [comment]
yet we're (you're) probably targeting the cheating community, which is quite retarded

**Comment by EchoVrHacks** [comment]
> yet we're (you're) probably targeting the cheating community, which is quite retarded

bruh

**Comment by kehrazy** [comment]
closing this due to it not having a huge lot of improvements, although having a `const val_t&& value` down the line might actually be a huge improvement.
