### ISSUE TITLE
Air control fix doesn't work on alot of mods.

### ISSUE THREAD

**Issue by Prince-Piplup** [es3n1n/portal2-internal#4]
The air control fix thing that removes the speedcap Only seems to work for vanilla portal. Doesn't work on portal stories mel or Portal reloaded just crashes when you try to enable it

**Comment by es3n1n** [comment]
Hey. 
Yes, I completely forgot to add the support of mel/reloaded versions for this feature. 
I will try to update this project as soon as I can. However, I'm not on my main pc til the end of the Jan, so you will probably have to wait.
PR welcome, and happy new year.

**Comment by Prince-Piplup** [comment]
Ahh alright. Let me know when you fix it. I'm quite enjoying using it.

**Comment by es3n1n** [comment]
https://github.com/es3n1n/portal2-internal/releases/tag/v0.0.3

**Comment by Prince-Piplup** [comment]
It works thanks i really like the mod
