### ISSUE TITLE
why would you use a language extension?

### ISSUE THREAD

**Issue by kehrazy** [es3n1n/portal2-internal#9]
https://github.com/es3n1n/portal2-internal/blob/823110d3ee743a8561cbb4f1b2e427ae1cbe4731/portal2-internal/hack/cfg/cfg.cpp#L22

---
Doesn't the __forceinline here suck?

Should we inline this in the first place, even? I assume this is going to destroy the optimizations of clang/msvc once we get a lot more config variables.

We/you probably should avoid compiler extensions.

Good work, big man.

**Comment by kehrazy** [comment]
Also, you *could* take a reference to `prefix` and std::move dem names. Your call.

**Comment by es3n1n** [comment]
Hey
Yes, you are right, i guess this forceinline opt was added at the time when there was only 1 chams option and i forgot to remove it.
As for other forceinlines, i think there are still some leftovers like this.
You can either create a PR by yourself, or i'll fix it by myself as soon as i'll get to my PC.

**Comment by kehrazy** [comment]
> You can either create a PR by yourself

Yeah, I would take this.

**Comment by es3n1n** [comment]
10388dfd5095e0616086e846d5e7fa26d52883cb
